### ISSUE TITLE
Updated changelog not committed back into repo

### ISSUE THREAD

**Issue by Ardesco** [release-flow/keep-a-changelog-action#67]
Not sure what I'm missing here but the CHANGELOG.md doesn't seem to get comitted back into my repo.  The release I'm tagging has the correct version and release notes so I'm not sure what I'm missing here, does this action just not commit back?

**Comment by richtea** [comment]
Hi @Ardesco thanks for trying out this action. You're quite right, the action doesn't commit, it just edits the changelog on disk. You need to add another step to your workflow to commit the changes. I'm a big fan of the Unix philosophy "Write programs that do one thing and do it well". 

I've got an example workflow [here](https://github.com/richtea/YAWN/blob/main/.github/workflows/prepare-release.yml) that runs this action followed by another action that creates a PR for the changelog updates - it's a little out of date because the core github actions are on a downlevel version, but it shows the basic principles. Or you could commit and push within your workflow - [this article](https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html) describes a few ways to do that.

**Comment by Ardesco** [comment]
That makes sense.  Would be useful to make that clear on the documentation as I spent a while trying to work out what was wrong with my config for the bump command before I raised this, so I'm hoping I'm not the only one... :)
